### ISSUE TITLE
how to activate multi speaker 

### ISSUE THREAD

**Issue by GemStox** [marty1885/paroli#9]
how to activate multi speaker  for your pair of onnx encoder and decoder model
on the web ui

**Comment by marty1885** [comment]
The model I uploaded is single speaker only. You'll need to train your own multi-speaker model and export them to have the multi speaker working. Unfortunately I do not have a multi speaker model I can share in public.

**Comment by GemStox** [comment]
thanks a lot dear for your reply  .
